help:
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'

build: ## build target will build our containers based on the docker-compose file. 
	

up: ## up will build and run our container based on the docker-compose file
	